### ISSUE TITLE
Launch MKEYS Network 

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#382]
For Ganesh's multiple bls key project

**Comment by AndyBoWu** [comment]
```[ec2-user@ip-172-31-37-52 harmony]$ ./scripts/go_executable_build.sh -s upload
upload: bin/harmony to s3://unique-bucket-bin/MKEYS/harmony
upload: bin/wallet to s3://unique-bucket-bin/MKEYS/wallet
upload: bin/bootnode to s3://unique-bucket-bin/MKEYS/bootnode
upload: bin/md5sum.txt to s3://unique-bucket-bin/MKEYS/md5sum.txt```

**Comment by AndyBoWu** [comment]
issue 1: the above script didn't create and upload the requires files to the proper path. The expected path should be: s3://unique-bucket-bin/MKEYS/static/*

**Comment by AndyBoWu** [comment]
```
2020/02/14 20:53:09 Stderr: fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x142e8b7, 0x2a)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:378 +0x47c

goroutine 1 [syscall]:
runtime.cgocall(0xf2a23c, 0xc00035b8e0, 0xc00019a201)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc00035b8b0 sp=0xc00035b878 pc=0x40476b
github.com/harmony-one/bls/ffi/go/bls._Cfunc_blsGetPublicKey(0xc000274120, 0xc00019edc0)
        _cgo_gotypes.go:164 +0x41 fp=0xc00035b8e0 sp=0xc00035b8b0 pc=0x5f4541
github.com/harmony-one/bls/ffi/go/bls.(*SecretKey).GetPublicKey(...)
        /home/ec2-user/go/pkg/mod/github.com/harmony-one/bls@v0.0.6/ffi/go/bls/bls.go:463
main.readMultiBlsKeys(0xc00025d960, 0xc00025d980, 0x15, 0xc00035b9f8)
        /home/ec2-user/harmony/cmd/harmony/main.go:282 +0x361 fp=0xc00035b998 sp=0xc00035b8e0 pc=0xf24321
main.setupConsensusKey(0x23718a0, 0xc00025d940, 0x1792580, 0xc0000bd2d0)
        /home/ec2-user/harmony/cmd/harmony/main.go:301 +0x3f2 fp=0xc00035ba30 sp=0xc00035b998 pc=0xf24832
main.setupLegacyNodeAccount(0x7ffe8fdd0f49, 0x7)
        /home/ec2-user/harmony/cmd/harmony/main.go:223 +0x9f fp=0xc00035baf8 sp=0xc00035ba30 pc=0xf23a6f
main.main()
        /home/ec2-user/harmony/cmd/harmony/main.go:601 +0x1bea fp=0xc00035bf60 sp=0xc00035baf8 pc=0xf2857a
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc00035bfe0 sp=0xc00035bf60 pc=0x4324fe
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc00035bfe8 sp=0xc00035bfe0 pc=0x45e411

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [chan receive]:
github.com/harmony-one/harmony/core.(*txSenderCacher).cache(0xc00013c2b0)
        /home/ec2-user/harmony/core/tx_cacher.go:63 +0x97
created by github.com/harmony-one/harmony/core.newTxSenderCacher
        /home/ec2-user/harmony/core/tx_cacher.go:55 +0x9f
```

**Comment by AndyBoWu** [comment]
Ganesha | HarmonyToday at 2:52 PM
can you deploy 0d99136881fda6347da5c47c3d36d0322ba38a68 on mkeys and try?
i reverted rj's commit

**Comment by gupadhyaya** [comment]
Fixed after reverting graceful shutdown commit.
