### ISSUE TITLE
No module named cryptography on newly provisioned explorer for PSTN

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#441]
```

DanielVDMYesterday at 11:45 PM
hey andy, im trying to setup a block explorer and im guessing I need certs (at least some is needed for the bash_profile). Try to use Cerbot to install but got 
[ec2-user@ip-172-31-8-249 ~]$  ./certbot-auto certonly -d explorer.ps.hmny.io --standalone --debug
Requesting to rerun ./certbot-auto with root privileges...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/_internal/main.py", line 10, in <module>
    import josepy as jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/interfaces.py", line 7, in <module>
    from josepy import errors, util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/util.py", line 7, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
ImportError: No module named cryptography
```

**Comment by AndyBoWu** [comment]
Fixed the issue a while ago for Minh when I was provisioning the dashboard for `explorer2.harmony.one` domain.

`sudo /opt/eff.org/certbot/venv/bin/pip install --upgrade certbot
`

**Comment by AndyBoWu** [comment]
Good news!!

```
[ec2-user@ip-172-31-8-249 ~]$ ./certbot-auto certonly -d explorer.ps.hmny.io --standalone --debug
Requesting to rerun ./certbot-auto with root privileges...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for explorer.ps.hmny.io
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/explorer.ps.hmny.io/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/explorer.ps.hmny.io/privkey.pem
   Your cert will expire on 2020-06-04. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot-auto
   again. To non-interactively renew *all* of your certificates, run
   "certbot-auto renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by AndyBoWu** [comment]
fixed
