### ISSUE TITLE
Unable to Start FE on network dashboard

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#442]
```
internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.openSync (fs.js:435:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.core.createServer (/home/ec2-user/projects/harmony-dashboard/node_modules/union/lib/core.js:73:16)
    at new HttpServer (/home/ec2-user/projects/harmony-dashboard/node_modules/http-server/lib/http-server.js:134:23)
    at Object.exports.createServer (/home/ec2-user/projects/harmony-dashboard/node_modules/http-server/lib/http-server.js:20:10)
    at listen (/home/ec2-user/projects/harmony-dashboard/node_modules/http-server/bin/http-server:123:27)
    at Object.<anonymous> (/home/ec2-user/projects/harmony-dashboard/node_modules/http-server/bin/http-server:92:3)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! harmony-website@1.0.0 serve: `http-server -p 2000 dist --ssl --cert $CERT_FILE --key $KEY_FILE`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the harmony-website@1.0.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2020-03-06T19_02_00_991Z-debug.log
```

**Comment by AndyBoWu** [comment]
$ npm install -g http-server
// Ref: https://superuser.com/a/1334552/531035
$ npm run build

**Comment by AndyBoWu** [comment]
**root cause**

```
[ec2-user@ip-172-31-8-249 harmony-dashboard]$ echo $CERT_FILE                                           │
                                                                                                        │
[ec2-user@ip-172-31-8-249 harmony-dashboard]$ echo $$KEY_FILE                                           │
9512KEY_FILE
```

**Comment by AndyBoWu** [comment]
```
[ec2-user@ip-172-31-8-249 harmony-dashboard]$ echo $KEY_FILE                                            │
/etc/letsencrypt/live/exploer.ps.hmny.io/privkey.pem                                                    │
[ec2-user@ip-172-31-8-249 harmony-dashboard]$ echo $CERT_FILE                                           │
/etc/letsencrypt/live/explorer.ps.hmny.io/fullchain.pem
```

**Comment by AndyBoWu** [comment]
This is a npm version issue IIRC. @mikedoan ?

<img width="840" alt="Screen Shot 2020-03-06 at 11 34 25 AM" src="https://user-images.githubusercontent.com/5258417/76116218-76c03180-5f9e-11ea-8405-2c1ed5ef413d.png">

**Comment by AndyBoWu** [comment]
my bad, typo from my side. 

Also, the ssl certificates are located here: `/etc/letsencrypt/archive/explorer.ps.hmny.io`, need to change their permission too.

**Comment by AndyBoWu** [comment]
bad commit from the code. had to revert the changes.
